practicas/1/RiosGamaliel/GamaRL.txt

ADD: Práctica 1 - Gamaliel Ríos

Agrego el nombre de Gamaliel Ríos

---

practicas/1/Camachojuan/Carloscamacho-glitch.txt

Agrego el nombre de Camacho Martinez Juan Carlos

---

practicas/1/ToledoDilan/Bael22.txt

Primera practica entregada, uso de git y almacenamiento en github.

Agrego el nombre de Dilan Toledo

---

practicas/1/OrganistaRicardo/Ricardo.txt

Agregue la carpeta OrganistaRicardo, y cree el archivo de texto Ricardo.txt con mi nombre y nombre de usuario dentro de este mismo

Agrego el nombre de Ricardo Organista

---

practicas/1/GarciaErik/Erik.txt

Agregue la carpeta GarciaErik, y cree el archivo de texto Erik.txt

Agrego el nombre de Erik Garcia

---

practicas/1/AerinMusetteMexLozano/aerinmus16.txt

Buenas noches profesor, estoy entregando la practica 1

Agrego el nombre de Aerin Musette Mex Lozano

---

practicas/1/VázquezFredin/FredinVazquez.txt

Realizo entrega de la práctica 1 agregando la carpeta con mi nombre, "VázquezFredin", y un archivo de texto con mi nombre real y usuario de github.

Agrego el nombre de Fredin Alberto Vázquez Martínez

---

practicas/1/MagnoOmar/Magno08.txt

Si esto se muestra, significa que he realizado correctamente la practica 1.

Agrego el nombre Omar Magno

---

practicas/1/SolisAlan/AlanDSol.txt

Agrego el nombre de Alan Solis

---

practicas/1/PabloConstantino/pablo.txt

Archivo de texto agregado a la carpeta PabloConstantino

Agrego mi nombre: Pablo Giovanni Constantino Cruz

---

practicas/1/RiveraMauricio/mauriciorivera18.txt

Se añadió un archivo txt con mi nombre real y el nombre de mi usuario de github como actividad de la practica 1

Agrego mi nombre al repositorio

---

practicas/1/ArmentaFabian/Fabian-Armenta.txt

Se crea la carpeta Armenta Fabian en practicas/1 y se crea el archivo txt con el nombre de usuario.

Agrego el nombre de Fabian Armenta

---

practicas/1/MartinezJulio/Julio.txt

Cree el archivo .txt y cambié la descripción

Practica 1

---

practicas/1/SierraNayeli/NayeSieruiz.txt

Agrego el nombre de Sierra Nayeli

---

practicas/1/MoralesFernando/MoralesFernando.txt

Entrego la practica 1 de Luis Fernando Morales Zilli

Agrego el nombre Fernando Morales 

---

practicas/1/PaniaguaEduardo/LaloPaniagua.txt

Por este medio realizo mi entrega correspondiente a la primera práctica.
Saludos :D

Agrego el nombre de Eduardo Paniagua

---

practicas/1/AranzuaCesar/cesar.txt

Cree el directorio y el fichero con mi nombre. LA interfaz de GitHub me aturde. Es todo y cuanto

Abogeniero entrando al curso de Gunnar

---

practicas/1/UriarteYahir/YahirUriarte.txt

Tarde pero al fin le entendí, soy de lento aprendizaje
Creación de archivo .txt con información solicitada

Agrego el nombre de Enrique Yahir Uriarte Ortiz

---

practicas/1/RangelJose/jose.txt

Agrego carpeta a la práctica 1 con mi nombre y apellido, junto con la línea de texto en un archivo con extensión .txt

Agrego el nombre de Jose Rangel

---

practicas/2/RiveraMauricio/B/cpuinfo.txt

Agrego el archivo de Mauricio Rivera para la practica 2B

---

practicas/2/FriasCamille/B/sistop_dir.txt

Agrego archivo de FriasCamille para la practica2b

---

practicas/2/ToledoDilan/B/cpuinfo.txt

hice un archivo con especificaciones de mi cpu no fake

Agrego el archivo de Dilan Toledo para la práctica 2B

---

practicas/2/MenesesErick/B/cpuinfo.txt

Buenas noches profesor, le hago entrega de la parte "B" de la practica 2

Agrego el archivo de Meneses Erick para la práctica 2B

---

practicas/2/ArmentaFabian/B/cpuinfo.txt

Agrego el archivo de Fabian Armenta para la practica 2B

Agrego el archivo de Fabian Armenta para la practica 2B

---

practicas/3/VázquezFredin/.gitignore
practicas/3/VázquezFredin/proceso_multiples_hijos.c

Entrega de la práctica 3 donde se realiza un programa que genera un archivo ejecutable, el cual deberá ser ignorado al momento de hacer push y así realizar el pull request.

Entrega de la práctica 3 por Fredin Vázquez

---

practicas/3/ArmentaFabian/.gitignore
practicas/3/ArmentaFabian/HelloWord_with_Threads.c

Se entrega la practica 3 la cual consiste en hacer un programa que genere un archivo ejecutable en el cual será ignorado posteriormente por medio de gitignore al momento de hacer un pull request

Entrega Practica 3 de Fabian Armenta

---

practicas/3/RuizLaura/.gitignore
practicas/3/RuizLaura/HolaMundoHilos.c

Hago entrega de la práctica 3, se incluye un archivo de implementación de hilos en C y un archivo .gitignore

Entrega de la práctica 3

---

tareas/1/SoteloAxel/reporte.txt
tareas/1/SoteloAxel/tarea1.py

Se incluye el reporte y el código de la tarea 1

Entrega de Tarea

---

tareas/1/UriarteYahir/IntersecciondeCaminos.py
tareas/1/UriarteYahir/IntersecciondeCaminosF.py
tareas/1/UriarteYahir/Tarea1_Uriarte_Yahir.txt

Agrego el archivo de texto (lo hice en _.txt_) y el archivo de código, en realidad son 2 archivos de código _.py_, pero el de la solución final  es el que se llama _IntersecciondeCaminosF.py_, el otro _IntersecciondeCaminos.py_ es una versión anterior del programa que presenta un caso que el código final no, en el archivo de texto explico más esto, sinceramente mi código "funciona" pero tiene limitaciones, una disculpa por la entrega

Agrego los archivos solicitados de la tarea.

---

tareas/1/AranzuaChavez-CarranzaOchoa/README.md
tareas/1/AranzuaChavez-CarranzaOchoa/tarea1.py

Entrega Tarea 1 Carranza-Aranzua

---

tareas/1/SolisAlan/Explicacion.txt
tareas/1/SolisAlan/santa.py

Buenas madrugadas profesor, le envió mi tarea 1. Gracias y buen día.
-Alan Solis.

Entrega de la tarea 1

---

proyectos/2/MarquezAxel-OronzorManases/.gitignore
proyectos/2/MarquezAxel-OronzorManases/README.md
proyectos/2/MarquezAxel-OronzorManases/planificacion_por_retroalimentacion_loteria.py
proyectos/2/MarquezAxel-OronzorManases/planificacion_por_retroalimentacion_loteria_2.py
proyectos/2/MarquezAxel-OronzorManases/planificacion_por_retroalimentacion_multinivel.py

Hola buenas noches profesor:
Le entregamos el proyecto numero dos, tuvimos muchos problemas al hacer el pull request donde terminamos por borrar de nuevo las ramas y subirlo, lamento la demora en la entrega.

Proyecto2 MarquezAxel-OronzorMontes

---

proyectos/2/RiveraMauricio-RuizLaura/README.md
proyectos/2/RiveraMauricio-RuizLaura/loteria.py
proyectos/2/RiveraMauricio-RuizLaura/retromulti.py

Entregamos nuestro proyecto, Al intentar correrlo en git marca errores con los acentos, pero con Python 3.10.11 en el simbolo de sistema si funciona bien.

Se entrega el segundo proyecto de Mauricio Rivera y Laura Ruiz

---

proyectos/2/PaniaguaEduardo/fb.py
proyectos/2/PaniaguaEduardo/loteria.py
proyectos/2/PaniaguaEduardo/preguntas.txt

Agrego archivos del proyecto 2

Entrega proyecto 2

---

proyectos/2/MagnoOmar-SolisAlan/Proyecto 2 Planificación por Retroa.txt
proyectos/2/MagnoOmar-SolisAlan/loteria.py
proyectos/2/MagnoOmar-SolisAlan/multinivel.py

Proyecto 2 creado por Magno Omar y Solis Alan.

Agrego el proyecto de Magno Omar y Solis Alan

---

tareas/2/SolisAlan/ref.py

Buenas madrugadas profesor, le envió mi tarea 2, buena noche.

Entrego la tarea 2

---

tareas/2/VázquezFredin-ArellanoIsrael/Información_de_un_directorio_T02.py

Se agregó la lectura de la entrada de parámetros por parte del usuario.

Agregando archivos de Tarea 2 con entrada de usuario
